server:
  port: 9008

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

#added
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/navigation
    username: postgres
    password: user
    platform: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

logging:
  level: debug